export const constants = {
  SEARCH_TIMEOUT_SMALL: 1777,
  SEARCH_TIMEOUT_BIG: 3000,
  MIN_PRODUCTS_ADDED_TO_CART: 5,
  MAX_PRODUCTS_ADDED_TO_CART: 10,
  AFTER_CLICK_TIMEOUT: 500,
  AFTER_SEARCH_TIMEOUT: 500,
  AFTER_DISCOUNT_TIMEOUT: 500,
  AFTER_REMOVE_TIMEOUT: 500,
  ONE_SECOND: 1000,
  HOME_URL: "http://app.local/",
  SIGN_IN_URL: "http://app.local/auth/signin",
  BURGER_BUTTON_WAIT: 500,
  EXCEL_IMPORT_TIMEOUT: 10000
}